{{- if .Values.vote.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vote-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    {{- range $key, $value := .Values.vote.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.vote.ingress.className }}
  rules:
  - http:
      paths:
      - path: {{ .Values.vote.ingress.path }}
        pathType: {{ .Values.vote.ingress.pathType }}
        backend:
          service:
            name: vote
            port:
              number: {{ .Values.vote.service.port }}
{{- end }}
